# Usa una imagen base de NGINX (servidor web)
FROM nginx:alpine

# Copia tus archivos al directorio que sirve NGINX
COPY . /usr/share/nginx/html

# Exponer el puerto 80 (por donde sirve NGINX)
EXPOSE 80
