name: Run Tests & Static Analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - uses: actions/checkout@v3

      # Construye el contenedor de Docker 
      - name: Build Docker Image
        run: docker build -t my-app .

      # Corre pruebas unitarias dentro del contenedor
      - name: Run Unit Tests
        run: docker run my-app npm test  

      # Análisis de código estático 
      - name: Run Static Code Analysis
        run: docker run my-app npm run lint
